CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL
);
-- Create the FILES table with properly defined data types and constraints
CREATE TABLE ADMIN.FILES (
    FILE_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FILE_NAME      VARCHAR2(255) NOT NULL,
    FILE_TYPE      VARCHAR2(50),
    FILE_SIZE      NUMBER,  -- File size in bytes
    FILE_PATH      VARCHAR2(500),  -- Storing file path as a string
    FILE_BOB   BLOB,  -- Store file content directly if needed
    UPLOAD_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPLOADED_BY    VARCHAR2(100),  -- Reference to user who uploaded the file
    USERNAME       VARCHAR2(100)
);

UPDATE FILES f
SET UPLOADED_BY = (SELECT ID FROM USERS u WHERE u.USERNAME = f.UPLOADED_BY);

ALTER TABLE FILES
ADD CONSTRAINT uk_file_name_uploaded_by UNIQUE (FILE_NAME, UPLOADED_BY);

CREATE INDEX idx_files_uploaded_by ON FILES(UPLOADED_BY);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(200) NOT NULL
);

-- Check the structure of the FILES table
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'FILES' AND OWNER = 'ADMIN';

-- Retrieve all file names from the FILES table
SELECT FILE_NAME FROM ADMIN.FILES;

GRANT EXECUTE ON DBMS_NETWORK_ACL_ADMIN TO TEST_USER;

GRANT DROP ANY TABLE TO test_user;

GRANT CREATE SESSION TO test_user;

GRANT INSERT ON FILES TO test_user;

GRANT UPDATE ON FILES TO TEST_USER;

GRANT DELETE ON FILES TO TEST_USER;

GRANT ALTER ON FILES TO TEST_USER;

DROP table file_storage;

ALTER USER TEST_USER QUOTA UNLIMITED ON DATA;


BEGIN
  DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(
    host => '<host_ip>',
    ace  => xs$ace_type(privilege_list => xs$name_list('connect'),
                         principal_name => 'PUBLIC',
                         principal_type => xs_acl.ptype_db));
END;
/
COMMIT;

SELECT constraint_name, constraint_type, search_condition
FROM user_constraints
WHERE table_name = 'FILES';

SELECT column_name
FROM user_cons_columns
WHERE constraint_name = 'UK_FILE_NAME_UPLOADED_BY';

SELECT file_name, uploaded_by, username FROM files;

select * from users

DELETE FROM files WHERE UPLOADED_BY ='';
COMMIT;

DELETE FROM users WHERE LOWER(username) = ''
COMMIT;


