CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL
);
-- Create the FILES table with properly defined data types and constraints
CREATE TABLE ADMIN.FILES (
    FILE_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FILE_NAME      VARCHAR2(255) NOT NULL,
    FILE_TYPE      VARCHAR2(50),
    FILE_SIZE      NUMBER,  -- File size in bytes
    FILE_PATH      VARCHAR2(500),  -- Storing file path as a string
    FILE_BOB   BLOB,  -- Store file content directly if needed
    UPLOAD_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPLOADED_BY    VARCHAR2(100)  -- Reference to user who uploaded the file
);

-- Check the structure of the FILES table
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'FILES' AND OWNER = 'ADMIN';

-- Retrieve all file names from the FILES table
SELECT FILE_NAME FROM ADMIN.FILES;

GRANT EXECUTE ON DBMS_NETWORK_ACL_ADMIN TO TEST_USER;

GRANT DROP ANY TABLE TO test_user;

GRANT CREATE SESSION TO test_user;

GRANT INSERT ON FILES TO test_user;

GRANT UPDATE ON FILES TO TEST_USER;

GRANT DELETE ON FILES TO TEST_USER;

GRANT ALTER ON FILES TO TEST_USER;

DROP table file_storage;

ALTER USER TEST_USER QUOTA UNLIMITED ON DATA;


BEGIN
  DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(
    host => '<host_ip>',
    ace  => xs$ace_type(privilege_list => xs$name_list('connect'),
                         principal_name => 'PUBLIC',
                         principal_type => xs_acl.ptype_db));
END;
/
COMMIT;