- name: Setup Storage Server
  hosts: storage_server
  become: yes  # Run commands as root
  tasks:
    - name: Enable the universe repository
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu/ focal universe'
        state: present
        
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ["python3", "python3-pip", "python3-venv", "unzip"]
        state: present
        
    - name: Install python-dotenv using pip
      pip:
        name: python-dotenv
        executable: pip3

    - name: Install Flask and cx_Oracle
      pip:
        name: ["flask", "cx_Oracle", "flask-login", "flask-wtf", "werkzeug", "authlib", "flask-jwt-extended"]

    # Ensure wallet_storagedb directory exists
    - name: Ensure wallet_storagedb directory exists
      file:
        path: /home/ubuntu/wallet_storagedb
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy wallet_storagedb folder to server
      copy:
        src: files/wallet_storagedb
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        
    - name: Secure .env file permissions
      file:
        path: /home/ubuntu/wallet_storagedb/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    # Oracle Instant Client Installation
    - name: Copy Instant Client ZIP files to the target system
      copy:
        src: "files/instant-client/instantclient-basic-linux.x64-23.7.0.25.01.zip"
        dest: "/home/ubuntu/instantclient-basic-linux.x64-23.7.0.25.01.zip"

    - name: Unzip Instant Client Basic package
      unarchive:
        src: "/home/ubuntu/instantclient-basic-linux.x64-23.7.0.25.01.zip"
        dest: "/home/ubuntu/"
        remote_src: yes

    # Enable IP Forwarding
    - name: Enable IP forwarding temporarily
      command: sysctl -w net.ipv4.ip_forward=1

    - name: Ensure IP forwarding is enabled persistently
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward=1"
        state: present

    - name: Apply sysctl settings
      command: sysctl -p

    # Deploy Flask Application
    - name: Deploy Flask API
      copy:
        src: files/app.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    
    - name: Deploy forms.py
      copy:
        src: files/forms.py
        dest: /home/ubuntu/forms.py
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Ensure templates directory exists
      file:
        path: /home/ubuntu/templates
        state: directory
        mode: '0755'

    - name: Ensure static directory exists
      file:
        path: /home/ubuntu/static
        state: directory
        mode: '0755'

    - name: Copy index html
      copy:
        src: files/templates/index.html
        dest: /home/ubuntu/templates/index.html

    - name: Copy files html
      copy:
        src: files/templates/files.html
        dest: /home/ubuntu/templates/files.html
        
    - name: Copy layout html
      copy:
        src: files/templates/layout.html
        dest: /home/ubuntu/templates/layout.html

    - name: Copy upload html
      copy:
        src: files/templates/upload.html
        dest: /home/ubuntu/templates/upload.html

    - name: Copy login html
      copy:
        src: files/templates/login.html
        dest: /home/ubuntu/templates/login.html
    
    - name: Copy register html
      copy:
        src: files/templates/register.html
        dest: /home/ubuntu/templates/register.html

    - name: Copy logout html
      copy:
        src: files/templates/logout.html
        dest: /home/ubuntu/templates/logout.html

    - name: Deploy favicon to static
      copy:
        src: files/static/favicon.ico
        dest: /home/ubuntu/static/favicon.ico

    - name: Deploy styles.css to static
      copy:
        src: files/static/styles.css
        dest: /home/ubuntu/static/styles.css

    # Start flask app